### GENERAL SETTINGS ###

# Site settings
title: Sensor Nodes
description: "Information on the design and use of ESP-8266 sensor
    nodes. ESP-8266 sensor nodes are an IoT implementation using MQTT over a
    WiFi network. Hardware design, PCB layout, embedded software on the
    ESP-8266, MQTT based server software and website development are all
    covered."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/" #important: start with /
url: "http://sensornodes.rockingdlabs.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks
social:
  - title: google-plus
    url: https://plus.google.com/+JERRYDUNMIRE/posts
  - title: github
    url: https://github.com/jdunmire

# Postal address (add as many lines as necessary). Shown in footer and
# on Contact page.
address:
  - lines: 
    - 3720 Benton St.
    - Santa Clara, CA 95051
    - United States.
#email: hello@solidtheme.com
#tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Jerry Dunmire
    position: Engineer/Maker
    text: Engineer by training and vocation,<br>Maker for life.
    img: team01.jpg
    social:
      - title: google-plus
        url: https://plus.google.com/+JERRYDUNMIRE/posts
      - title: github
        url: https://github.com/jdunmire
#      - title: envelope #use for email address
#        url: mailto:name@domain.com

# Short text. Shown in footer on every page and also separately on Home
# and Contact page.
about: "Battery operated remote sensors for makers."

